project:
  type: website
  output-dir: docs

website:
  title: "Brandon LeBeau"
  description: "Academic website and blog"
  
  navbar:
    background: "#101730"
    foreground: "#faf8f8"
    #logo: false
    title: "Brandon LeBeau"
    left:
      - text: "Educate-R"
        href: /posts/
      - text: "Publications"
        href: /publications/
      - text: "Presentations" 
        href: /presentations/
      - text: "R Packages"
        href: /packages/
      - text: "Workshops"
        href: /workshops/
      - text: "About"
        href: /about/

  sidebar:
    style: "floating"
    
  page-footer:
    background: "#101730"
    foreground: "#faf8f8"
    left: |
      <div class="social-links">
        <a href="mailto:brandon-lebeau@uiowa.edu" title="Email">
          <i class="fa fa-envelope"></i>
        </a>
        <a href="https://twitter.com/blebeau11" title="Twitter">
          <i class="fa fa-twitter"></i>
        </a>
        <a href="https://github.com/lebebr01" title="GitHub">
          <i class="fa fa-github"></i>
        </a>
      </div>
    right: |
      Brandon LeBeau

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true
    toc-location: right
    highlight-style: github
    link-external-newwindow: true
    
comments:
  hypothesis: false

execute:
  freeze: auto