---
title: Examining High School Student Engagement and Critical Factors in Dropout Prevention
description: There is a well-known positive relation between student engagement and
  a host of school outcomes.
author:
- name: Nathan Stevenson
- name: Jessica Swain-Bradway
- name: Brandon LeBeau
date: '2019-05-14'
categories:
- Research

---

## Abstract

There is a well-known positive relation between student engagement and a host of school outcomes. The following article describes a study that explores a commonly used tool for measuring engagement in high schools. Specifically, this study examined internal validity, factor structure, and the relation between factors of engagement (e.g. social, emotional, and academic) and outcomes of school attendance and suspension rates. Data were collected for 7,718 students in 9th through 12th grade. Engagement was measured using the High School Survey of Student Engagement (HSSSE). Analyses raise concern over the degree to which the structure of HSSSE fits with established constructs of engagement. Implications and directions for future research are discussed.

## Citation

Stevenson, Nathan, Swain-Bradway, Jessica, LeBeau, Brandon (2019). Examining High School Student Engagement and Critical Factors in Dropout Prevention. **Assessment for Effective Intervention*, (in press)*.

## Links

[Link to Journal](https://journals.sagepub.com/doi/abs/10.1177/1534508419859655){.pub-link}

::: {.pub-info}
**Publication:** *Assessment for Effective Intervention*, (in press)  **Authors:** Nathan Stevenson, Jessica Swain-Bradway, Brandon LeBeau  **Date:** May 14, 2019  **DOI:** 10.1177/1534508419859655
:::


