---
title: 'Differentiating Among Gifted Learners: A Comparison of Classical Test Theory
  and Item Response Theory on Above-Level Testing'
description: This study investigated the application of item response theory (IRT)
  to expand the range of ability estimates for gifted (hereinafter referred to as
  high-achieving) students’ performance on an abo...
author:
- name: Brandon LeBeau
- name: Susan G. Assouline
- name: Duhita Mahatmya
- name: Ann Lupkowski-Shoplik
date: '2020-06-01'
categories:
- IRT
- Gifted Education

---

## Abstract

This study investigated the application of item response theory (IRT) to expand the range of ability estimates for gifted (hereinafter referred to as high-achieving) students’ performance on an above-level test. Using a sample of 4th – 6th grade high-achieving students (n = 1,893), we conducted a case study to compare estimates from classical test theory (CTT) and IRT. First, we estimated means, standard deviations, and percentiles of the students using CTT statistics. Next, we fitted a two- parameter IRT model using a multi-group framework to represent the different grade levels. We compared CTT and IRT results to determine the value-added of using an IRT approach in identifying high-achieving students through the Talent Search Model of above-level testing. Benefits of IRT, compared to CTT and with respect to the Talent Search Model, include invariance of item parameters across groups of individuals and invariance of an individual’s ability across tests of the same construct. IRT also uses the response string of individuals’ scores; therefore, test items can differentially inform the latent aptitude construct. Implications for academic talent identification with the Talent Search Model and development of academic talent are discussed.

## Citation

LeBeau, Brandon, Assouline, Susan G., Mahatmya, Duhita, Lupkowski-Shoplik, Ann (2020). Differentiating Among Gifted Learners: A Comparison of Classical Test Theory and Item Response Theory on Above-Level Testing. **Gifted Child Quarterly*, 64 (3), 219-237*.

## Links

[Link to Journal](https://doi.org/10.1177/0016986220924050){.pub-link} [PDF](https://doi.org/10.17077/pp.004118){.pub-link}

::: {.pub-info}
**Publication:** *Gifted Child Quarterly*, 64 (3), 219-237  **Authors:** Brandon LeBeau, Susan G. Assouline, Duhita Mahatmya, Ann Lupkowski-Shoplik  **Date:** June 01, 2020  **DOI:** 10.1177/0016986220924050
:::

