---
title: 'Creating a developmental scale to account for heterotypic continuity in development:
  A simulation study'
description: Many psychological constructs show heterotypic continuity—their behavioral
  manifestations change with development (e.
author:
- name: Isaac T. Peterson
- name: Brandon LeBeau
- name: Daniel Choe
date: '2020-06-01'
categories:
- Research

---

## Abstract

Many psychological constructs show heterotypic continuity—their behavioral manifestations change with development (e.g., externalizing problems). However, research has paid little attention to how to account for heterotypic continuity. A promising approach to account for heterotypic continuity is creating a developmental scale using vertical scaling. We conducted a simulation to compare creating a developmental scale using vertical scaling to traditional approaches of assessing a construct over time. Traditional approaches that failed to account for heterotypic continuity resulted in less accurate growth estimates, at the person- and group-level.  Findings suggest that ignoring heterotypic continuity may result in faulty developmental inferences. Creating a developmental scale with vertical scaling is recommended to link different measures across time and account for heterotypic continuity.

## Citation

Peterson, Isaac T., LeBeau, Brandon, Choe, Daniel (2020). Creating a developmental scale to account for heterotypic continuity in development: A simulation study. **Child Development**.

## Links

[Link to Journal](https://dx.doi.org/10.1111/cdev.13433){.pub-link}

::: {.pub-info}
**Publication:** *Child Development*  **Authors:** Isaac T. Peterson, Brandon LeBeau, Daniel Choe  **Date:** June 01, 2020  **DOI:** 10.1111/cdev.13433
:::


