---
title: 'Development of Internalizing Problems From Adolescence to Emerging Adulthood:
  Accounting for Heterotypic Continuity With Vertical Scaling'
description: Manifestations of internalizing problems, such as specific symptoms of
  anxiety and depression, can change across development, even if individuals show
  strong continuity in rank-order levels of inte...
author:
- name: Isaac T. Peterson
- name: Oliver Lindhiem
- name: Brandon LeBeau
- name: John E. Bates
- name: Gregory S. Pettit
- name: Jennifer E. Lansford
- name: Kenneth A. Dodge
date: '2017-11-20'
categories:
- Psychology
- IRT
- Longitudinal

---

## Abstract

Manifestations of internalizing problems, such as specific symptoms of anxiety and depression, can change across development, even if individuals show strong continuity in rank-order levels of internalizing problems. This illustrates the concept of heterotypic continuity, and raises the question of whether common measures might be construct-valid for one age but not another. This study examines mean-level changes in internalizing problems across a long span of development at the same time as accounting for heterotypic continuity by using age-appropriate, changing measures. Internalizing problems from age 14–24 were studied longitudinally in a community sample (N = 585), using Achenbach’s Youth Self-Report (YSR) and Young Adult Self-Report (YASR). Heterotypic continuity was evaluated with an item response theory (IRT) approach to vertical scaling, linking different measures over time to be on the same scale, as well as with a Thurstone scaling approach. With vertical scaling, internalizing problems peaked in mid-to-late adolescence and showed a group-level decrease from adolescence to early adulthood, a change that would not have been seen with the approach of using only age-common items. Individuals’ trajectories were sometimes different than would have been seen with the common-items approach. Findings support the importance of considering heterotypic continuity when examining development and vertical scaling to account for heterotypic continuity with changing measures.

## Citation

Peterson, Isaac T., Lindhiem, Oliver, LeBeau, Brandon, Bates, John E., Pettit, Gregory S., Lansford, Jennifer E., Dodge, Kenneth A. (2017). Development of Internalizing Problems From Adolescence to Emerging Adulthood: Accounting for Heterotypic Continuity With Vertical Scaling. **Developmental Psychology*, 54 (3), 586*.

## Links

[Link to Journal](https://psycnet.apa.org/doi/10.1037/dev0000449){.pub-link}

::: {.pub-info}
**Publication:** *Developmental Psychology*, 54 (3), 586  **Authors:** Isaac T. Peterson, Oliver Lindhiem, Brandon LeBeau, John E. Bates, Gregory S. Pettit, Jennifer E. Lansford, Kenneth A. Dodge  **Date:** November 20, 2017  **DOI:** 10.1037/dev0000449
:::


