---
title: Impact of Serial Correlation Misspecification with the Linear Mixed Model
description: Linear mixed models are popular models for use with clustered and longitudinal
  data due to their ability to model variation at different levels of clustering.
author:
- name: Brandon LeBeau
date: '2016-05-01'
categories:
- Journal Article
- Statistics
- Mixed Models
- Longitudinal

---

## Abstract

Linear mixed models are popular models for use with clustered and longitudinal data due to their ability to model variation at different levels of clustering. A Monte Carlo study was used to explore the impact of assumption violations on the bias of parameter estimates and the empirical type I error rates. Simulated conditions included in this study are: simulated serial correlation structure, fitted serial correlation structure, random effect distribution, cluster sample size, and number of measurement occasions. Results showed that the fixed effects are unbiased, but the random components tend to be overestimated and the empirical Type I error rates tend to be inflated. Implications for applied researchers were discussed.

## Citation

LeBeau, Brandon (2016). Impact of Serial Correlation Misspecification with the Linear Mixed Model. **Journal of Modern Applied Statistical Methods*, 15 (1), 389-416*.

## Links

[Link to Journal](http://digitalcommons.wayne.edu/cgi/viewcontent.cgi?article=1915&context=jmasm){.pub-link}

::: {.pub-info}
**Publication:** *Journal of Modern Applied Statistical Methods*, 15 (1), 389-416  **Authors:** Brandon LeBeau  **Date:** May 01, 2016
:::


