---
title: 'Reading Comprehension Assessment: The Effect of Reading the Items Aloud Before
  or After Reading the Passage'
description: This study investigated the effects of imposing task- or process-oriented
  reading behaviors on reading comprehension assessment performance.
author:
- name: Deborah K. Reed
- name: Nathan Stevenson
- name: Brandon LeBeau
date: '2019-05-20'
categories:
- Journal Article
- Assessment

---

## Abstract

This study investigated the effects of imposing task- or process-oriented reading behaviors on reading comprehension assessment performance. Students in Grades 5-8 (N = 275) were randomly assigned to hear multiple-choice items read aloud before or after reading a test passage and when they were and were not allowed access to the passage while answering items. A confirmatory factor analysis found a one-factor model with all test items loading on the comprehension latent variable fit better than treating literal, inferential, and evaluative items as three separate variables. Subsequently, a structural equation model explored whether testing condition or other covariates (state assessment score and student demographics) explained variance in reading comprehension assessment performance. In Grades 5-6, significant positive effects were found for students who kept the text while answering items, regardless of whether or not they previewed the items. In Grades 7-8, no significant differences were found for the four testing conditions.

## Citation

Reed, Deborah K., Stevenson, Nathan, LeBeau, Brandon (2019). Reading Comprehension Assessment: The Effect of Reading the Items Aloud Before or After Reading the Passage. **The Elementary School Journal*, (in press)*.

## Links

[Link to Journal](https://www.journals.uchicago.edu/doi/abs/10.1086/705784){.pub-link}

::: {.pub-info}
**Publication:** *The Elementary School Journal*, (in press)  **Authors:** Deborah K. Reed, Nathan Stevenson, Brandon LeBeau  **Date:** May 20, 2019  **DOI:** 10.1086/705784
:::


