---
title: Creating a Developmental Scale to Chart the Development of Psychopathology
  with Different Informants and Measures across Time
description: RDoC aims to advance a dimensional, multilevel understanding of psychopathology
  across the lifespan.
author:
- name: Isaac T. Petersen
- name: Brandon LeBeau
date: '2020-06-01'
categories:
- Journal Article
- Psychology

---

## Abstract

RDoC aims to advance a dimensional, multilevel understanding of psychopathology across the lifespan. Two key challenges exist in applying a developmental perspective to RDoC: First, the most accurate informants for assessing a person’s psychopathology often differ across development (e.g., parents and teachers may be better informants of a person’s externalizing problems in early childhood, whereas peer- and self-report may also be important to assess in adolescence). Second, many constructs change in their behavioral manifestation across development (i.e., heterotypic continuity). Thus, different informants and measures across time may be necessary to account for the construct’s changing manifestation. The challenge of using different informants and measures of a construct across time is ensuring that the same construct is assessed in a comparable way across development. Vertical scaling creates a developmental scale to link scores from changing informants and measures to account for heterotypic continuity and study people’s development of psychopathology across the lifespan. This is the first study that created a developmental scale to assess people’s development by putting different informants and measures on the same scale. We examined the development of externalizing problems from ages 2–15 years (N=1,364) using annual ratings by mothers, fathers, teachers, other caregivers, and self-report. The developmental scale linked different informants and measures on the same scale. This allowed us to chart people’s growth trajectories and to identify multilevel risk factors, including poor verbal comprehension. Creating a developmental scale may be crucial to advance RDoC’s goal of studying the development of psychopathology across the lifespan.

## Citation

Petersen, Isaac T., LeBeau, Brandon (2020). Creating a Developmental Scale to Chart the Development of Psychopathology with Different Informants and Measures across Time. **Journal of Abnormal Psychology**.

::: {.pub-info}
**Publication:** *Journal of Abnormal Psychology*  **Authors:** Isaac T. Petersen, Brandon LeBeau  **Date:** June 01, 2020
:::

