---
title: 'Studying a Moving Target in Development: The Challenge and Opportunity of
  Heterotypic Continuity'
description: Many psychological constructs show heterotypic continuity—their behavioral
  manifestations change with development but their meaning remains the same (e.
author:
- name: Isaac T. Petersen
- name: Daniel E. Choe
- name: Brandon LeBeau
date: '2020-06-01'
categories:
- Journal Article
- Psychology
- Longitudinal

---

## Abstract

Many psychological constructs show heterotypic continuity—their behavioral manifestations change with development but their meaning remains the same (e.g., externalizing problems). However, research has paid little attention to how to account for heterotypic continuity. Conceptual and methodological challenges of heterotypic continuity may prevent researchers from examining lengthy developmental spans. Developmental theory requires that measurement accommodate changes in manifestation of constructs. Simulation and empirical work demonstrate that failure to account for heterotypic continuity when collecting or analyzing longitudinal data results in faulty developmental inferences. Accounting for heterotypic continuity may require using different measures across time with approaches that link measures on a comparable scale. Creating a developmental scale (i.e., developmental scaling) is recommended to link measures across time and account for heterotypic continuity, which is crucial in understanding development across the lifespan. The current synthesized review defines heterotypic continuity, describes how to identify it, and presents solutions to account for it. We note challenges of addressing heterotypic continuity, and propose steps in leveraging opportunities it creates to advance empirical study of development.

## Citation

Petersen, Isaac T., Choe, Daniel E., LeBeau, Brandon (2020). Studying a Moving Target in Development: The Challenge and Opportunity of Heterotypic Continuity. **Developmental Review**.

## Links

[Link to Journal](https://doi.org/10.1016/j.dr.2020.100935){.pub-link}

::: {.pub-info}
**Publication:** *Developmental Review*  **Authors:** Isaac T. Petersen, Daniel E. Choe, Brandon LeBeau  **Date:** June 01, 2020  **DOI:** 10.1016/j.dr.2020.100935
:::

