---
title: Language Ability in the Development of Externalizing Behavior Problems in Childhood
description: Poorer language ability has been shown to predict the development of
  externalizing behavior problems such as aggression and conduct problems.
author:
- name: Isaac T. Petersen
- name: Brandon LeBeau
date: '2019-12-31'
categories:
- Journal Article
- Education
- Psychology

---

## Abstract

Poorer language ability has been shown to predict the development of externalizing behavior problems such as aggression and conduct problems. However, the developmental process that links poorer language ability to externalizing problems is unclear. The present study examined (a) whether withinchild changes in language ability predict within-child changes in externalizing problems, (b) whether social skills are a potential mechanism that explains the association between language ability and externalizing problems, and (c) whether there are sex-related differences in the association between language ability and externalizing problems. The present study examined these questions in children (N = 1,364) followed annually from 4 to 10 years of age. Language ability was assessed by a measure of receptive language (i.e., vocabulary). Externalizing problems were rated by mothers and teachers. Social skills were rated by mothers, fathers, and teachers. Findings showed that within-child changes in language ability predicted within-child changes in externalizing problems, even controlling for the family’s income-to-needs ratio. We found that social skills partially mediated the association between poorer language ability and later externalizing problems, but this was limited to a between-person effect. There was not strong evidence of sex-related differences in the association. Findings suggest that language ability may play a role in the development of externalizing problems for boys and girls, and that social skills may be a mechanism that partially explains how poorer language ability leads to the development of externalizing problems. Or, alternatively, language ability, social skills, and externalizing problems may partially share common causes.

## Citation

Petersen, Isaac T., LeBeau, Brandon (2019). Language Ability in the Development of Externalizing Behavior Problems in Childhood. **Journal of Educational Psychology**.

## Links

[Link to Journal](https://psycnet.apa.org/record/2020-04185-001){.pub-link}

::: {.pub-info}
**Publication:** *Journal of Educational Psychology*  **Authors:** Isaac T. Petersen, Brandon LeBeau  **Date:** December 31, 2019
:::


