---
title: Misspecification of the random effect structure Implications for the linear
  mixed model
description: The linear mixed model is a commonly used model for longitudinal or nested
  data due to its ability to account for the dependency of nested data.
author:
- name: Brandon LeBeau
date: '2018-05-08'
categories:
- Mixed Models
- Longitudinal

---

## Abstract

The linear mixed model is a commonly used model for longitudinal or nested data due to its ability to account for the dependency of nested data. Researchers typically rely on the random effects to adequately account for the dependency due to correlated data, however serial correlation can also be used. If the random effect structure is misspecified (perhaps due to convergence problems), can the addition of serial correlation overcome this misspecification and allow for unbiased estimation and accurate inferences? This study explored this question with a simulation. Simulation results show that the fixed effects are unbiased, however inflation of the empirical type I error rate occurs when a random effect is missing from the model. Implications for applied researchers are discussed.

## Citation

LeBeau, Brandon (2018). Misspecification of the random effect structure Implications for the linear mixed model. **.

## Links

[PDF](https://ir.uiowa.edu/pq_pubs/2/){.pub-link}

::: {.pub-info}
**Publication:**   **Authors:** Brandon LeBeau  **Date:** May 08, 2018
:::

