---
title: A multi-institutional study of the relationship between high school mathematics
  achievement and performance in introductory college statistics
description: In this study we examined the effects of prior mathematics achievement
  and completion of a commercially developed, National Science Foundation-funded,
  or University of Chicago School Mathematics Pr...
author:
- name: Danielle Dupuis
- name: Amanuel Medhanie
- name: Michael R. Harwell
- name: Brandon LeBeau
- name: Debra Monson
- name: Thomas R. Post
date: '2012-05-01'
categories:
- Journal Article
- Education
- Statistics

---

## Abstract

In this study we examined the effects of prior mathematics achievement and completion of a commercially developed, National Science Foundation-funded, or University of Chicago School Mathematics Project high school mathematics curriculum on achievement in students’ first college statistics course. Specifically, we examined the relationship between students’ high school mathematics achievement and high school mathematics curriculum on the difficulty level of students’ first college statistics course, and on the grade earned in that course. In general, students with greater prior mathematics achievement took more difficult statistics courses and earned higher grades in those courses. The high school mathematics curriculum a student completed was unrelated to statistics grades and course-taking.

## Citation

Dupuis, Danielle, Medhanie, Amanuel, Harwell, Michael R., LeBeau, Brandon, Monson, Debra, Post, Thomas R. (2012). A multi-institutional study of the relationship between high school mathematics achievement and performance in introductory college statistics. **Statistics Education Research Journal*, 11(4), 4 - 20*.

## Links

[Link to Journal](https://www.stat.auckland.ac.nz/~iase/serj/SERJ11(1)_Dupuis.pdf){.pub-link} [PDF](https://www.stat.auckland.ac.nz/~iase/serj/SERJ11(1)_Dupuis.pdf){.pub-link}

::: {.pub-info}
**Publication:** *Statistics Education Research Journal*, 11(4), 4 - 20  **Authors:** Danielle Dupuis, Amanuel Medhanie, Michael R. Harwell, Brandon LeBeau, Debra Monson, Thomas R. Post  **Date:** May 01, 2012
:::


