---
title: The role of the accuplacer mathematics placement test on a student's first
  college mathematics course
description: The first college mathematics course a student enrolls in is often affected
  by performance on a college mathematics placement test.
author:
- name: Amanuel Medhanie
- name: Danielle Dupuis
- name: Brandon LeBeau
- name: Michael R. Harwell
- name: Thomas R. Post
date: '2012-03-27'
categories: Education

---

## Abstract

The first college mathematics course a student enrolls in is often affected by performance on a college mathematics placement test. Yet validity evidence of mathematics placement tests remains limited, even for nationally standardized placement tests, and when it is available usually consists of examining a student’s subsequent performance in mathematics courses. This study expands on existing literature by considering whether a nationally standardized college mathematics placement test (ACCUPLACER) contributes to the prediction of enrollment and success in developmental and nondevelopmental mathematics courses above and beyond prediction associated with the ACT mathematics test. Results for a sample of more than 1,300 students from 20 postsecondary institutions suggest that ACCUPLACER does not contribute to either the prediction of enrollment or subsequent success in such courses, and that comparable information is provided by using the ACT mathematics score alone. Implications of these findings are discussed.

## Citation

Medhanie, Amanuel, Dupuis, Danielle, LeBeau, Brandon, Harwell, Michael R., Post, Thomas R. (2012). The role of the accuplacer mathematics placement test on a student's first college mathematics course. **Educational and Psychological Measurement*, 72(2), 332 - 351*.

## Links

[Link to Journal](https://doi.org/10.1177%2F0013164411417620){.pub-link}

::: {.pub-info}
**Publication:** *Educational and Psychological Measurement*, 72(2), 332 - 351  **Authors:** Amanuel Medhanie, Danielle Dupuis, Brandon LeBeau, Michael R. Harwell, Thomas R. Post  **Date:** March 27, 2012
:::


