---
title: A Multisite Study of High School Mathematics Curricula and the Impact of Taking
  a Developmental Mathematics Course in College
description: The relationship between high school mathematics curricula and the likelihood
  of students who enroll in a developmental (non-credit bearing) course in college
  taking additional mathematics courses ...
author:
- name: Michael R. Harwell
- name: Danielle Dupuis
- name: Thomas R. Post
- name: Amanuel Medhanie
- name: Brandon LeBeau
date: '2014-06-01'
categories: Education

---

## Abstract

The relationship between high school mathematics curricula and the likelihood of students who enroll in a developmental (non-credit bearing) course in college taking additional mathematics courses was studied. The results showed that high school mathematics curriculum, years of high school mathematics completed, and A C T mathematics scores were related to developmental mathematics course-taking, but curriculum was not related to the subsequent mathematics course-taking o f students who began college with developmental mathematics.  The results have important implications for educational researchers and policymakers at the college and high school levels.

## Citation

Harwell, Michael R., Dupuis, Danielle, Post, Thomas R., Medhanie, Amanuel, LeBeau, Brandon (2014). A Multisite Study of High School Mathematics Curricula and the Impact of Taking a Developmental Mathematics Course in College. **Educational Research Quarterly*, 37.3, 3 - 22*.

## Links

[Link to Journal](https://search.proquest.com/openview/d21810c7ed29be396e8cbe93b460b256/1?pq-origsite=gscholar&cbl=48020){.pub-link}

::: {.pub-info}
**Publication:** *Educational Research Quarterly*, 37.3, 3 - 22  **Authors:** Michael R. Harwell, Danielle Dupuis, Thomas R. Post, Amanuel Medhanie, Brandon LeBeau  **Date:** June 01, 2014
:::


