---
title: Student and High-School Characteristics related to completing a science, technology,
  engineering or mathematics (STEM) major in college
description: '**Background:** The importance of increasing the number of US college
  students completing degrees in science, technology, engineering or mathematics (STEM)
  has prompted calls for research to provid...'
author:
- name: Brandon LeBeau
- name: Michael R. Harwell
- name: Debra Monson
- name: Danielle Dupuis
- name: Amanuel Medhanie
- name: Thomas R. Post
date: '2012-03-19'
categories:
- Education
- Mixed Models

---

## Abstract

**Background:** The importance of increasing the number of US college students completing degrees in science, technology, engineering or mathematics (STEM) has prompted calls for research to provide a better understanding of factors related to student participation in these majors, including the impact of a stu- dent’s high-school mathematics curriculum.
**Purpose:** This study examines the relationship between various student and high-school characteristics and completion of a STEM major in college. Of spe- cific interest is the influence of a student’s high-school mathematics curriculum on the completion of a STEM major in college.
**Sample:** The sample consisted of approximately 3500 students from 229 high schools. Students were predominantly Caucasian (80%), with slightly more males than females (52% vs 48%).
**Design and method:** A quasi-experimental design with archival data was used for students who enrolled in, and graduated from, a post-secondary institution in the upper Midwest. To be included in the sample, students needed to have com- pleted at least three years of high-school mathematics. A generalized linear mixed model was used with students nested within high schools. The data were cross-sectional.
**Results:** High-school predictors were not found to have a significant impact on the completion of a STEM major. Significant student-level predictors included ACT mathematics score, gender and high-school mathematics GPA.
**Conclusions:** The results provide evidence that on average students are equally prepared for the rigorous mathematics coursework regardless of the high-school mathematics curriculum they completed.

## Citation

LeBeau, Brandon, Harwell, Michael R., Monson, Debra, Dupuis, Danielle, Medhanie, Amanuel, Post, Thomas R. (2012). Student and High-School Characteristics related to completing a science, technology, engineering or mathematics (STEM) major in college. **Research in Science & Technological Education*, 30:1, 17 - 28*.

## Links

[Link to Journal](https://doi.org/10.1080/02635143.2012.659178){.pub-link}

::: {.pub-info}
**Publication:** *Research in Science & Technological Education*, 30:1, 17 - 28  **Authors:** Brandon LeBeau, Michael R. Harwell, Debra Monson, Danielle Dupuis, Amanuel Medhanie, Thomas R. Post  **Date:** March 19, 2012  **DOI:** 10.1080/02635143.2012.659178
:::


