---
title: A Multi-Institutional Study of High School Mathematics Curricula and College
  Mathematics Achievement and Course Taking
description: This study examined the relationship between high school mathematics
  curricula and student achievement and course-taking patterns over 4 years of college
  course taking for a sample of over 10,000 s...
author:
- name: Michael R. Harwell
- name: Thomas R. Post
- name: Amanuel Medhanie
- name: Danielle Dupuis
- name: Brandon LeBeau
date: '2013-06-01'
categories:
- Journal Article
- Education

---

## Abstract

This study examined the relationship between high school mathematics curricula and student achievement and course-taking patterns over 4 years of college course taking for a sample of over 10,000 students from 32 postsecondary 4-year institutions. Three types of curricula were studied: National Science Foundation (NSF) funded curricula, the University of Chicago School Mathematics Project curriculum, and commercially developed curricula. The major result was that high school mathematics curricula were unrelated to college mathematics achievement or students’ course-taking patterns for students who began college with precalculus (college algebra) or a more difficult course. However, students of the NSF-funded curricula were statistically more likely to begin their college mathematics at the developmental level. Implications of these results for research and practice are discussed.

## Citation

Harwell, Michael R., Post, Thomas R., Medhanie, Amanuel, Dupuis, Danielle, LeBeau, Brandon (2013). A Multi-Institutional Study of High School Mathematics Curricula and College Mathematics Achievement and Course Taking. **Journal for Research in Mathematics Education*, 44.5, 742 - 774*.

## Links

[Link to Journal](https://www.jstor.org/stable/10.5951/jresematheduc.44.5.0742){.pub-link}

::: {.pub-info}
**Publication:** *Journal for Research in Mathematics Education*, 44.5, 742 - 774  **Authors:** Michael R. Harwell, Thomas R. Post, Amanuel Medhanie, Danielle Dupuis, Brandon LeBeau  **Date:** June 01, 2013  **DOI:** 10.5951/jresematheduc.44.5.0742
:::


