---
title: 'Ability and Prior Distribution Mismatch: An Exploration of Common-Item Linking
  Methods'
description: Linking of two forms is an important task when using item response theory,
  particularly when two forms are administered to nonequivalent groups.
author:
- name: Brandon LeBeau
date: '2017-05-18'
categories: IRT

---

## Abstract

Linking of two forms is an important task when using item response theory, particularly when two forms are administered to nonequivalent groups. When linking with characteristic curve methods, the ability distribution and weights associated with that distribution can be used to weight observations differently. These are commonly specified as equally spaced intervals from −4 to 4, but other options or distributional forms can be specified. The use of these different distributions and weights of the ability distributions will be explored with a Monte Carlo simulation. Primary simulation conditions will include sample size, number of items, number of common items, ability distribution, and randomly varying population transformation constants. Study results show that the linking weights have little impact on the estimation of the linking constants; however, the underlying ability distribution of examinees does have significant impact. Implications for applied researchers will be discussed.

## Citation

LeBeau, Brandon (2017). Ability and Prior Distribution Mismatch: An Exploration of Common-Item Linking Methods. **Applied Psychological Methods*, 41 (7), 545-560*.

## Links

[Link to Journal](http://journals.sagepub.com/doi/full/10.1177/0146621617707508){.pub-link}

::: {.pub-info}
**Publication:** *Applied Psychological Methods*, 41 (7), 545-560  **Authors:** Brandon LeBeau  **Date:** May 18, 2017  **DOI:** 10.1177/0146621617707508
:::


