---
title: 'Model misspecification and assumption violations with the linear mixed model:
  A meta-analysis'
description: This meta-analysis attempts to synthesize the Monte Carlo literature
  for the linear mixed model under a longitudinal framework.
author:
- name: Brandon LeBeau
- name: Yoon Ah Song
- name: Wei Cheng Liu
date: '2018-12-01'
categories:
- Mixed Models
- Longitudinal

---

## Abstract

This meta-analysis attempts to synthesize the Monte Carlo literature for the linear mixed model under a longitudinal framework. The meta-analysis aims to inform researchers about conditions that are important to consider when evaluating model assumptions and adequacy. In addition, the meta-analysis may be helpful to those wishing to design future Monte Carlo simulations in identifying simulation conditions. The current meta-analysis will use the empirical type I error rate as the effect size and Monte Carlo simulation conditions will be coded to serve as moderator variables. The type I error rate for the fixed and random effects will be explored as the primary dependent variable. Effect sizes were coded from 13 studies, resulting in a total of 4,002 and 621 effect sizes for fixed and random effects respectively. Meta-regression and proportional odds models were used to explore variation in the empirical type I error rate effect sizes. Implications for applied researchers and researchers planning new Monte Carlo studies will be explored.

## Citation

LeBeau, Brandon, Song, Yoon Ah, Liu, Wei Cheng (2018). Model misspecification and assumption violations with the linear mixed model: A meta-analysis. **Sage Open*, 8 (4)*.

## Links

[Link to Sage Open](https://doi.org/10.1177/2158244018820380){.pub-link} [PDF](https://ir.uiowa.edu/pq_pubs/1/){.pub-link}

::: {.pub-info}
**Publication:** *Sage Open*, 8 (4)  **Authors:** Brandon LeBeau, Yoon Ah Song, Wei Cheng Liu  **Date:** December 01, 2018  **DOI:** 10.1177/2158244018820380
:::


