---
title: Student eligibility for a free lunch as an SES measure in education research
description: The use of eligibility for a free lunch as a measure of a student's socioeconomic
  status continues to be a fixture of quantitative education research.
author:
- name: Michael R Harwell
- name: Brandon LeBeau
date: '2010-03-01'
categories: Education

---

## Abstract

The use of eligibility for a free lunch as a measure of a student's socioeconomic status continues to be a fixture of quantitative education research. Despite its popularity, it is unclear that education researchers are familiar with what student eligibility for a free lunch does (and does not) represent. The authors examine the National School Lunch Program, which is responsible for certifying students as eligible for a free lunch, and conclude that free lunch eligibility is a poor measure of socioeconomic status, which suffers from important deficiencies that can bias inferences. A table characterizing key strengths and weaknesses of variables used as measures of socioeconomic status is provided to facilitate comparisons.

## Citation

Harwell, Michael R, LeBeau, Brandon (2010). Student eligibility for a free lunch as an SES measure in education research. **Educational Researcher*, 39(2), 120 - 131*.

## Links

[Link to Journal](https://doi.org/10.3102%2F0013189X10362578){.pub-link}

::: {.pub-info}
**Publication:** *Educational Researcher*, 39(2), 120 - 131  **Authors:** Michael R Harwell, Brandon LeBeau  **Date:** March 01, 2010
:::


