---
title: Power Analysis by Simulation using R and simglm
description: Power is a task that is commonly done prior to collecting data for a
  primary study.
author:
- name: Brandon LeBeau
date: '2019-06-11'
categories:
- R
- Mixed Models
- Longitudinal

---

## Abstract

Power is a task that is commonly done prior to collecting data for a primary study. In most cases closed-form solutions are used to estimate power which may statistical assumptions to be able to perform the computations, for example assume residuals are normally distributed. In real-world data, these statistical assumptions may not hold, therefore estimates of power when these assumptions are assumed will likely be inflated. Power by simulation is another way to compute power estimates and offers significant flexibility to the user to explore the impact of various statistical assumption violations may have on power. This tutorial uses the simglm R package to perform the power by simulation. The simglm package provides a framework to simulate data from generalized linear mixed models which includes a wide variety of models. In addition, functions to perform replications and to compute power estimate summaries are available for users to take advantage of. Two worked examples are shown, one for a two-sample t-test and another within a repeated measures or longitudinal framework.

## Citation

LeBeau, Brandon (2019). Power Analysis by Simulation using R and simglm. **.

## Links

[PDF](https://ir.uiowa.edu/pq_pubs/3/){.pub-link} [Code](https://github.com/lebebr01/simglm_power){.pub-link}

::: {.pub-info}
**Publication:**   **Authors:** Brandon LeBeau  **Date:** June 11, 2019
:::

