---
title: Outcomes assessment of case-based writing exercises in a veterinary clinical
  pathology course
description: Our second-year core clinical pathology course uses free-response case-based
  learning exercises in an otherwise traditional lecture or laboratory course format
  to augment the development of skills ...
author:
- name: Leslie Sharkey
- name: Helen Michael
- name: Brandon LeBeau
- name: Bruce Center
- name: Deb Wingert
date: '2012-08-01'
categories:
- Journal Article
- Education
- Longitudinal
- Assessment

---

## Abstract

Our second-year core clinical pathology course uses free-response case-based learning exercises in an otherwise traditional lecture or laboratory course format to augment the development of skills in application of knowledge and critical thinking and clinical reasoning. We previously reported increased learner confidence accompanied by perceived improvements in understanding and ability to apply information, along with enhanced feelings of preparedness for examinations that students attributed to the case-based exercises. The current study prospectively follows a cohort of students to determine the ability of traditional multiple-choice versus free-response case-based assessments to predict future academic performance and to determine if the perceived value of the case-based exercises persists through the curriculum. Our data show that after holding multiple-choice scores constant, better performance on case-based free-response exercises led to higher GPA and better class rank in the second and third years and better class rank in the fourth year. Students in clinical rotations reported that the case-based approach was superior to traditional lecture or multiple-choice exam format for learning clinical reasoning, retaining factual information, organizing information, communicating medical information clearly to colleagues in clinical situations, and preparing high quality medical records. In summary, this longitudinal study shows that case-based free-response writing assignments are efficacious above and beyond standard measures in determining students’ GPAs and class rank and in students’ acquisition of knowledge, skills, and clinical reasoning. Students value these assignments and overwhelmingly find them an efficient use of their time, and these opinions are maintained even two years following the course.

## Citation

Sharkey, Leslie, Michael, Helen, LeBeau, Brandon, Center, Bruce, Wingert, Deb (2012). Outcomes assessment of case-based writing exercises in a veterinary clinical pathology course. **Journal of Veterinary Medical Education*, 39.4, 396 - 403*.

## Links

[Link to Journal](https://doi.org/10.3138/jvme.0312.020R1){.pub-link}

::: {.pub-info}
**Publication:** *Journal of Veterinary Medical Education*, 39.4, 396 - 403  **Authors:** Leslie Sharkey, Helen Michael, Brandon LeBeau, Bruce Center, Deb Wingert  **Date:** August 01, 2012  **DOI:** 10.3138/jvme.0312.020R1
:::


